//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceBC
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", ConfigurationName="ServiceReferenceBC.AppService_Port")]
    public interface AppService_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AppService:GetConsultantNos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceBC.GetConsultantNos_Result> GetConsultantNosAsync(ServiceReferenceBC.GetConsultantNos request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AppService:GetProjectNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceBC.GetProjectNames_Result> GetProjectNamesAsync(ServiceReferenceBC.GetProjectNames request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AppService:GetProjectNos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceBC.GetProjectNos_Result> GetProjectNosAsync(ServiceReferenceBC.GetProjectNos request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AppService:GetProjectOptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceBC.GetProjectOptions_Result> GetProjectOptionsAsync(ServiceReferenceBC.GetProjectOptions request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AppService:InsertProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceBC.InsertProject_Result> InsertProjectAsync(ServiceReferenceBC.InsertProject request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AppService:InsertTimeReg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceBC.InsertTimeReg_Result> InsertTimeRegAsync(ServiceReferenceBC.InsertTimeReg request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsultantNos", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AppService", IsWrapped=true)]
    public partial class GetConsultantNos
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=0)]
        public string project;
        
        public GetConsultantNos()
        {
        }
        
        public GetConsultantNos(string project)
        {
            this.project = project;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsultantNos_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AppService", IsWrapped=true)]
    public partial class GetConsultantNos_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=0)]
        public string return_value;
        
        public GetConsultantNos_Result()
        {
        }
        
        public GetConsultantNos_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectNames", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AppService", IsWrapped=true)]
    public partial class GetProjectNames
    {
        
        public GetProjectNames()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectNames_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AppService", IsWrapped=true)]
    public partial class GetProjectNames_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=0)]
        public string return_value;
        
        public GetProjectNames_Result()
        {
        }
        
        public GetProjectNames_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectNos", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AppService", IsWrapped=true)]
    public partial class GetProjectNos
    {
        
        public GetProjectNos()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectNos_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AppService", IsWrapped=true)]
    public partial class GetProjectNos_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=0)]
        public string return_value;
        
        public GetProjectNos_Result()
        {
        }
        
        public GetProjectNos_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectOptions", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AppService", IsWrapped=true)]
    public partial class GetProjectOptions
    {
        
        public GetProjectOptions()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectOptions_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AppService", IsWrapped=true)]
    public partial class GetProjectOptions_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=0)]
        public string return_value;
        
        public GetProjectOptions_Result()
        {
        }
        
        public GetProjectOptions_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertProject", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AppService", IsWrapped=true)]
    public partial class InsertProject
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=1)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=2)]
        public string mail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime birthDate;
        
        public InsertProject()
        {
        }
        
        public InsertProject(string name, string lastName, string mail, System.DateTime birthDate)
        {
            this.name = name;
            this.lastName = lastName;
            this.mail = mail;
            this.birthDate = birthDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertProject_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AppService", IsWrapped=true)]
    public partial class InsertProject_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=0)]
        public bool return_value;
        
        public InsertProject_Result()
        {
        }
        
        public InsertProject_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTimeReg", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AppService", IsWrapped=true)]
    public partial class InsertTimeReg
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=0)]
        public string project;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=1)]
        public string consultant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=2)]
        public int minutes;
        
        public InsertTimeReg()
        {
        }
        
        public InsertTimeReg(string project, string consultant, int minutes)
        {
            this.project = project;
            this.consultant = consultant;
            this.minutes = minutes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTimeReg_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AppService", IsWrapped=true)]
    public partial class InsertTimeReg_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AppService", Order=0)]
        public bool return_value;
        
        public InsertTimeReg_Result()
        {
        }
        
        public InsertTimeReg_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface AppService_PortChannel : ServiceReferenceBC.AppService_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class AppService_PortClient : System.ServiceModel.ClientBase<ServiceReferenceBC.AppService_Port>, ServiceReferenceBC.AppService_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AppService_PortClient() : 
                base(AppService_PortClient.GetDefaultBinding(), AppService_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AppService_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppService_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(AppService_PortClient.GetBindingForEndpoint(endpointConfiguration), AppService_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppService_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AppService_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppService_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AppService_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppService_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceBC.GetConsultantNos_Result> ServiceReferenceBC.AppService_Port.GetConsultantNosAsync(ServiceReferenceBC.GetConsultantNos request)
        {
            return base.Channel.GetConsultantNosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBC.GetConsultantNos_Result> GetConsultantNosAsync(string project)
        {
            ServiceReferenceBC.GetConsultantNos inValue = new ServiceReferenceBC.GetConsultantNos();
            inValue.project = project;
            return ((ServiceReferenceBC.AppService_Port)(this)).GetConsultantNosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceBC.GetProjectNames_Result> ServiceReferenceBC.AppService_Port.GetProjectNamesAsync(ServiceReferenceBC.GetProjectNames request)
        {
            return base.Channel.GetProjectNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBC.GetProjectNames_Result> GetProjectNamesAsync()
        {
            ServiceReferenceBC.GetProjectNames inValue = new ServiceReferenceBC.GetProjectNames();
            return ((ServiceReferenceBC.AppService_Port)(this)).GetProjectNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceBC.GetProjectNos_Result> ServiceReferenceBC.AppService_Port.GetProjectNosAsync(ServiceReferenceBC.GetProjectNos request)
        {
            return base.Channel.GetProjectNosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBC.GetProjectNos_Result> GetProjectNosAsync()
        {
            ServiceReferenceBC.GetProjectNos inValue = new ServiceReferenceBC.GetProjectNos();
            return ((ServiceReferenceBC.AppService_Port)(this)).GetProjectNosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceBC.GetProjectOptions_Result> ServiceReferenceBC.AppService_Port.GetProjectOptionsAsync(ServiceReferenceBC.GetProjectOptions request)
        {
            return base.Channel.GetProjectOptionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBC.GetProjectOptions_Result> GetProjectOptionsAsync()
        {
            ServiceReferenceBC.GetProjectOptions inValue = new ServiceReferenceBC.GetProjectOptions();
            return ((ServiceReferenceBC.AppService_Port)(this)).GetProjectOptionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceBC.InsertProject_Result> ServiceReferenceBC.AppService_Port.InsertProjectAsync(ServiceReferenceBC.InsertProject request)
        {
            return base.Channel.InsertProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBC.InsertProject_Result> InsertProjectAsync(string name, string lastName, string mail, System.DateTime birthDate)
        {
            ServiceReferenceBC.InsertProject inValue = new ServiceReferenceBC.InsertProject();
            inValue.name = name;
            inValue.lastName = lastName;
            inValue.mail = mail;
            inValue.birthDate = birthDate;
            return ((ServiceReferenceBC.AppService_Port)(this)).InsertProjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceBC.InsertTimeReg_Result> ServiceReferenceBC.AppService_Port.InsertTimeRegAsync(ServiceReferenceBC.InsertTimeReg request)
        {
            return base.Channel.InsertTimeRegAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBC.InsertTimeReg_Result> InsertTimeRegAsync(string project, string consultant, int minutes)
        {
            ServiceReferenceBC.InsertTimeReg inValue = new ServiceReferenceBC.InsertTimeReg();
            inValue.project = project;
            inValue.consultant = consultant;
            inValue.minutes = minutes;
            return ((ServiceReferenceBC.AppService_Port)(this)).InsertTimeRegAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AppService_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AppService_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://mybc:7047/CRONUS USA, Inc./Codeunit/AppService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AppService_PortClient.GetBindingForEndpoint(EndpointConfiguration.AppService_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AppService_PortClient.GetEndpointAddress(EndpointConfiguration.AppService_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            AppService_Port,
        }
    }
}
